version: "3.5"
services:
  AppConfigService:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "8080:8080"
    command: bash -c "
      npm install
      && node ./dist/server.js
      "
