- id: prod
  name: Prod
  authority: com.example.config
  sort: 100
  keyValues:
    - key: START_URL
      value:
- id: testpage
  name: Test Page
  authority: com.example.config
  sort: 999
  keyValues:
    - key: START_URL
      value: https://example.com/test-page/
